import React,{useEffect,useState} from "react"; import {createRoot} from "react-dom/client"; import "./style.css";
const API=import.meta.env.VITE_API_BASE||"http://localhost:8080/api";
async function request(path:string,init:RequestInit={}){const token=sessionStorage.getItem("admin_token"); const r=await fetch(API+path,{...init,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}}); if(r.status===401){sessionStorage.clear();throw new Error("登录已过期")} if(!r.ok)throw new Error((await r.text())||"请求失败"); return r.json();}
function App(){const [token,setToken]=useState(sessionStorage.getItem("admin_token")); const [page,setPage]=useState("dashboard"); const [stats,setStats]=useState<any>({}); const [users,setUsers]=useState<any[]>([]); const [error,setError]=useState(""); useEffect(()=>{if(token){request("/admin/dashboard").then(setStats).catch(e=>setError(e.message));}},[token]); if(!token)return <Login onLogin={t=>{sessionStorage.setItem("admin_token",t);setToken(t)}}/>; const loadUsers=()=>request("/admin/users").then(d=>setUsers(d.items)); return <div className="shell"><aside><h1>粤语学习</h1><p className="muted">运营后台</p><button onClick={()=>setPage("dashboard")}>概览</button><button onClick={()=>{setPage("users");loadUsers()}}>用户管理</button><button onClick={()=>setPage("scenes")}>场景内容</button><button className="logout" onClick={()=>{sessionStorage.clear();setToken(null)}}>退出登录</button></aside><main><header><span>内容运营中心</span><b>管理员</b></header>{error&&<div className="error">{error}</div>}{page==="dashboard"&&<><h2>概览</h2><div className="cards"><div><small>用户数</small><strong>{stats.users??"-"}</strong></div><div><small>场景数</small><strong>{stats.scenes??"-"}</strong></div></div></>}{page==="users"&&<><h2>用户管理</h2><table><thead><tr><th>ID</th><th>用户名</th><th>昵称</th><th>手机号</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.id}</td><td>{u.username}</td><td>{u.nickname}</td><td>{u.phone||"-"}</td></tr>)}</tbody></table></>}{page==="scenes"&&<ScenePanel/>}</main></div>}
function ScenePanel(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{request("/admin/scenes").then(d=>setItems(d.items))},[]);return <><h2>场景内容</h2><table><thead><tr><th>标题</th><th>地点</th><th>角色</th><th>内置</th></tr></thead><tbody>{items.map(s=><tr key={s.id}><td>{s.emoji||""} {s.title}</td><td>{s.place}</td><td>{s.roleA} / {s.roleB}</td><td>{s.builtin?"是":"否"}</td></tr>)}</tbody></table></>}
function Login({onLogin}:{onLogin:(t:string)=>void}){const [u,setU]=useState("admin"),[p,setP]=useState(""),[e,setE]=useState("");return <div className="login"><form onSubmit={async ev=>{ev.preventDefault();try{const d=await request("/admin/auth/login",{method:"POST",body:JSON.stringify({username:u,password:p})});onLogin(d.token)}catch(x:any){setE(x.message)}}}><h1>粤语学习后台</h1><p>管理员登录</p><input value={u} onChange={e=>setU(e.target.value)} placeholder="账号"/><input value={p} onChange={e=>setP(e.target.value)} placeholder="密码" type="password"/><button>登录</button>{e&&<div className="error">{e}</div>}</form></div>}; createRoot(document.getElementById("root")!).render(<App/>);



